name: tests

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v1
    - name: python setup
      uses: actions/setup-python@v1
      with:
        python-version: 3.6
    - name: install flupy
      run: |
        python -m pip install --upgrade pip
        pip install -e ".[dev]"

    - name: run tests
      run: |
        pytest --cov=nebulo src/test --cov-report=xml

    - name: upload coverage to Codecov
      uses: codecov/codecov-action@v1
      with:
        token: ${{ secrets.CODECOV_TOKEN }}
        file: ./coverage.xml
        flags: unittests
        name: codecov-umbrella
        fail_ci_if_error: true<Paste>
