name: Tests

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v1
    - name: Python Setup
      uses: actions/setup-python@v1
      with:
        python-version: 3.6
    - name: Install Flupy
      run: |
        python -m pip install --upgrade pip
        pip install -e ".[dev]"

    - name: Run Tests
      run: |
        pytest
